// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

### Suche id, modell, typ und version von allen Autosn
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos {
    id
    modell
    typ
    version
  }
}

### Suche modell, typ, modellnr und version von einem Auto mit vorhandener Auto-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  auto(id: "000000000000000000000001") {
    modell
    typ
    modellnr
    version
  }
}

### Suche modell von einem Auto mit nicht-vorhandener Auto-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  auto(id: "999999999999999999999999") {
    modell
  }
}

### Suche typ von Autosn mit vorhandenem Modell
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos(modell: "Alpha") {
    typ
  }
}

### Suche modell, typ und herstellorte von Autosn mit vorhandenem Modell
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos(modell: "a") {
    modell
    typ
    herstellorte
  }
}

### Suche typ von Autosn mit NICHT-vorhandenem Modell
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos(modell: "Nichtvorhanden") {
    typ
  }
}
